# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         a2pdf
version:      1.12
version_from: bin/a2pdf
installdirs:  site
requires:
    PDF::API2:                     0.6

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
